---
title: "R Notebook"
output: html_notebook
---

```{r}

```

下面是用boxplot来画K线图
```{r}
library(quantmod)

stock <- getSymbols("AAPL", from = "2017-01-01", auto.assign = FALSE)

head(stock)

names(stock) <- sub("^.*\\.", "", names(stock))

head(stock)

stock <- data.frame(stock)

stock$date <- index(stock)
stock$lower <- pmin(stock$Open, stock$Close)
stock$upper <- pmax(stock$Open, stock$Close)
stock$ymin  <- stock$Low
stock$ymax  <- stock$High
stock$color <- ifelse(stock$Open < stock$Close, "red", "green")

head(stock)

library(ggplot2)

p <- ggplot(stock)

p <- p + geom_boxplot(mapping = aes(x = date,
                                    lower = lower, 
                                    upper = upper,
                                    middle = upper,
                                    ymin = ymin,
                                    ymax = ymax,
                                    group = date,
                                    fill = color),
                      stat = 'identity')

p
```

老版本的ggplot2的middle可以设置为NULL，新版本的不行了，所以，只能把middle设为upper或者lower，上边或下边会变粗，很难看。

所以，改进后是这样的，先画一条竖线，再画一个矩形：

```{r}
library(quantmod)
library(ggplot2)

stock <- getSymbols("AAPL", from = "2017-01-01", auto.assign = FALSE)

stock <- as.data.frame(stock)

head(stock)

names(stock) <- gsub("^.+\\.","",names(stock))

head(stock)

stock$date       <- index(stock)
stock$candleDown <- pmin(stock$Open, stock$Close)
stock$candleUp   <- pmax(stock$Open, stock$Close)
stock$candleHigh <- stock$High
stock$candleLow  <- stock$Low
# stock$color      <- ifelse(stock$Open > stock$Close, "red", "green")
stock$fill      <- ifelse(stock$Open > stock$Close, "black", "white")

gg <- ggplot(stock, aes(x = date))

gg <- gg + geom_linerange(aes(ymin = Low, ymax = High))
gg <- gg + geom_rect(aes(xmin=date-0.3, xmax=date+0.3, ymax=candleUp, ymin=candleDown, fill=fill), colour="black") + scale_fill_identity()

# gg <- gg + geom_line(aes(x=date, y=Close), colour="orange")+ylab("price")
gg

```


下面看下怎么画外汇数据，数据是从MT4导出来的

```{r}
library(tidyverse)
library(ggthemes)

fx <- read_csv("EURUSD5.csv", col_names = c("date", "time", "open", "high", "low", "close", "volumn"))
fx <- fx %>% filter(date == "2017.08.30")
fx

gg <- ggplot(fx, aes(x = time))

gg <- gg + geom_linerange(aes(ymin = low, ymax = high))

gg <- gg + geom_rect(aes(xmin=time - 20, xmax=time + 20, ymax=ifelse(open>close, open, close), ymin=ifelse(open>close, close, open), fill=ifelse(open > close, "black", "white")), colour="black") + scale_fill_identity()
gg

```

堆叠：

```{r}
library(tidyverse)
library(ggthemes)
library(grid)

fx_dxy <- read_csv("SPT_DXY60.csv", col_names = c("date", "time", "open", "high", "low", "close", "volumn"))
fx_eur <- read_csv("EURUSD60.csv",  col_names = c("date", "time", "open", "high", "low", "close", "volumn"))
fx_gld <- read_csv("SPT_GLD60.csv", col_names = c("date", "time", "open", "high", "low", "close", "volumn"))

# fx_dxy$currency <- "SPT_DXY"
# fx_eur$currency <- "EURUSD"
# fx_gld$currency <- "SPT_GLD"

# fx <- rbind(fx_dxy, rbind(fx_eur, fx_gld))

fx_dxy <- fx_dxy %>% filter(date == "2017.08.23")
fx_eur <- fx_eur %>% filter(date == "2017.08.23")
fx_gld <- fx_gld %>% filter(date == "2017.08.23")

gg1 <- ggplot(fx_dxy, aes(x = time))
gg1 <- gg1 + geom_linerange(aes(ymin = low, ymax = high))
gg1 <- gg1 + geom_rect(aes(xmin = time - 200, xmax = time + 200, ymax = ifelse(open > close, open, close), ymin = ifelse(open > close, close, open), fill = ifelse(open > close, "black", "white")), colour = "black") + scale_fill_identity()
gg1 <- gg1 + scale_x_continuous(labels = NULL) + xlab(NULL)

gg2 <- ggplot(fx_eur, aes(x = time))
gg2 <- gg2 + geom_linerange(aes(ymin = low, ymax = high))
gg2 <- gg2 + geom_rect(aes(xmin = time - 200, xmax = time + 200, ymax = ifelse(open > close, open, close), ymin = ifelse(open > close, close, open), fill = ifelse(open > close, "black", "white")), colour = "black") + scale_fill_identity()
gg2 <- gg2 + scale_x_continuous(labels = NULL) + xlab(NULL)

gg3 <- ggplot(fx_gld, aes(x = time))
gg3 <- gg3 + geom_linerange(aes(ymin = low, ymax = high))
gg3 <- gg3 + geom_rect(aes(xmin = time - 200, xmax = time + 200, ymax = ifelse(open > close, open, close), ymin = ifelse(open > close, close, open), fill = ifelse(open > close, "black", "white")), colour = "black") + scale_fill_identity()

multiplot <- function(..., plotlist = NULL, cols = 1, layout = NULL) {
    plots <- c(list(...), plotlist)
    numPlots = length(plots)
    if (is.null(layout)) {
        layout <- matrix(seq(1, cols * ceiling(numPlots/cols)), ncol = cols, nrow = ceiling(numPlots/cols))
    }
    if (numPlots == 1) {
        print(plots[[1]])
    } else {
        grid.newpage()
        pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
        for (i in 1:numPlots) {
            matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
            print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row, layout.pos.col = matchidx$col))
        }
    }
}

multiplot(gg1, gg2, gg3)
```

画蜡烛图太丑了，还是线图吧：

要不要作归一化处理，还是分形

```{r}
rm(list = ls())
library(tidyverse)
library(ggthemes)
library(grid)

fx_dxy <- read_csv("SPT_DXY60.csv", col_names = c("date", "time", "open", "high", "low", "close", "volumn"))
fx_eur <- read_csv("EURUSD60.csv",  col_names = c("date", "time", "open", "high", "low", "close", "volumn"))
fx_gld <- read_csv("SPT_GLD60.csv", col_names = c("date", "time", "open", "high", "low", "close", "volumn"))

fx_dxy <- fx_dxy %>% filter(date == "2017.08.23")
fx_eur <- fx_eur %>% filter(date == "2017.08.23")
fx_gld <- fx_gld %>% filter(date == "2017.08.23")

gg1 <- ggplot(fx_dxy) + geom_line(aes(x = time, y = close))
gg1 <- gg1 + xlab(NULL) + ylab("SPT_DXY") # + scale_x_continuous(labels = NULL)

gg2 <- ggplot(fx_eur) + geom_line(aes(x = time, y = close))
gg2 <- gg2 + xlab(NULL) + ylab("EURUSD") # + scale_x_continuous(labels = NULL)

gg3 <- ggplot(fx_gld) + geom_line(aes(x = time, y = close))
gg3 <- gg3 + ylab("SPT_GLD")

multiplot <- function(..., plotlist = NULL, cols = 1, layout = NULL) {
    plots <- c(list(...), plotlist)
    numPlots = length(plots)
    if (is.null(layout)) {
        layout <- matrix(seq(1, cols * ceiling(numPlots/cols)), ncol = cols, nrow = ceiling(numPlots/cols))
    }
    if (numPlots == 1) {
        print(plots[[1]])
    } else {
        grid.newpage()
        pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
        for (i in 1:numPlots) {
            matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
            print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row, layout.pos.col = matchidx$col))
        }
    }
}

multiplot(gg1, gg2, gg3)

```


作归一化处理：

```{r}
rm(list = ls())
library(tidyverse)
library(ggthemes)

fx_dxy <- read_csv("SPT_DXY60.csv", col_names = c("date", "time", "open", "high", "low", "close", "volumn"))
fx_eur <- read_csv("EURUSD60.csv",  col_names = c("date", "time", "open", "high", "low", "close", "volumn"))
fx_gld <- read_csv("SPT_GLD60.csv", col_names = c("date", "time", "open", "high", "low", "close", "volumn"))

fx_dxy <- fx_dxy %>% filter(date == "2017.08.23")
fx_eur <- fx_eur %>% filter(date == "2017.08.23")
fx_gld <- fx_gld %>% filter(date == "2017.08.23")

fx_dxy <- cbind(fx_dxy, close2 = scale(fx_dxy$close))
fx_eur <- cbind(fx_eur, close2 = scale(fx_eur$close))
fx_gld <- cbind(fx_gld, close2 = scale(fx_gld$close))


# f1 <- tibble(currency = "SPT_DXY", time = fx_dxy$time, close = scale(fx_dxy$close))


fx <- rbind(tibble(currency = "SPT_DXY", time = fx_dxy$time, close = fx_dxy$close2),
            rbind(tibble(currency = "EURUSD", time = fx_eur$time, close = fx_eur$close2),
                  tibble(currency = "SPT_GLD", time = fx_gld$time, close = fx_gld$close2)))

fx

gg <- ggplot(fx) + geom_line(aes(x = time, y = close, color = currency))
gg

# gg <- ggplot(fx) + geom_smooth(aes(x = time, y = close, color = currency), se = F)


```




























```{r}
require(quantmod)
require(ggplot2)

getSymbols('AAPL')
x<-AAPL
start <- Sys.Date()-200
end <- Sys.Date()

#Pass an OHLC object into this function
#also pass two dates formatted as.Date()
ggChartSeries <- function(x, start, end){
  
  # the below is done redundantly for ease of maintenance later on
  #First, strip OHLC data (need to vectorize)
  date <- as.Date(time(x))
  open <- as.vector(Op(x))
  high <- as.vector(Hi(x))
  low <- as.vector(Lo(x))
  close <- as.vector(Cl(x))
  
  #Then build the data frame
  xSubset <-data.frame('date'=date,'open'=open,'high'= high,'low'=low,'close'=close)
  
  #We want to construct our candlesticks  
  xSubset$candleLower <- pmin(xSubset$open, xSubset$close)
  xSubset$candleMiddle <- NA
  xSubset$candleUpper <- pmax(xSubset$open, xSubset$close)
  xSubset$fill <- ''
  xSubset$fill[xSubset$open < xSubset$close] = 'white'
  xSubset$fill[xSubset$fill ==''] = 'red'
  
  #Add Moving Averages
  xSubset$ma200 <- SMA(xSubset$close, 200)
  xSubset$ma50 <- SMA(xSubset$close, 50)
  
  #Trim Data
  xSubset <-subset(xSubset, xSubset$date > start & xSubset$date < end)
  
  #Graphing Step
  g <- ggplot(xSubset, aes(x=date, lower=candleLower, middle=candleUpper, upper=candleUpper, ymin=low, ymax=high)) 
  g <- g + geom_boxplot(stat='identity', aes(group=date, fill=fill))
  g <- g + geom_line(aes(x=date, y=ma50))+ geom_line(aes(x=date, y=ma200))
  g 
}

#call our graphing function
ggChartSeries(AAPL, start, end)

```

